### PR TITLE
Add Validator How-To

### PR DESCRIPTION
**Pull request by deeayeen**

### CODE REVIEW

**Comment by sunify** [comment]
@deeayeen have you tried to do all steps?

**Comment by deeayeen** [comment]
@sunify @johannbarbie 
Steps 2 and 3 are actually unnecessary, removing them and resubmitting now.

**Comment by sunify** [comment]
@deeayeen thanks. But you didn't answer my question

**Comment by deeayeen** [comment]
@sunify Yes I tried both steps, I noticed they were redirecting to an unfinished web page. I left the steps on there assuming the pages would eventually be live. I removed the steps as they are not necessary for the process or are completed anyway in other steps.

**Comment by sunify** [comment]
@deeayeen i mean the whole instruction

**Comment by deeayeen** [comment]
@sunify 
I do not have the capability to become a validator so I can not test the instructions, the instructions were given to me by several developers on the team

**Comment by articobandurini** [comment]
After learning details of the issue I would recommend to accept the fact that both sides of this dispute are not completely correct, therefore my proposed solution is to pay the worker partially and decline this pull request, then probably re-create the bounty with improved specs. @sunify @johannbarbie @troggy opinions?

**Comment by troggy** [comment]
closing. Details:
https://github.com/leapdao/leapdao-docs/issues/18#issuecomment-515435463
https://leapdao.slack.com/archives/CAAGW85BR/p1562601184016800

**Comment by deeayeen** [comment]
Thank you for resolving this, I deeply appreciate the teams consideration. @troggy

**Pull request closed without merging**
